[Interface]
PrivateKey = <приватный_ключ_wg_ВМ>
Address = 10.30.0.2/24

[Peer]
PublicKey = <публичный_ключ_VPS>
Endpoint = <IP_VPS>:51822
AllowedIPs = 10.10.10.0/24, 192.168.122.0/24, 10.30.0.2/32
PersistentKeepalive = 25
